### ISSUE TITLE
Not able to run bower install

### ISSUE THREAD

**Issue by onhate** [EduwHS/AngularTemplate#1]
![image](https://cloud.githubusercontent.com/assets/980905/5877383/5e224866-a306-11e4-8abe-9514859c3271.png)

**Comment by EduwHS** [comment]
Hello. Could you try using https?
git config --global url."https://".insteadOf git://
npm install

**Comment by onhate** [comment]
Removing the "^" in front of the versions fixed the npm install.

"devDependencies": {
    "grunt": "0.4.5",
    "grunt-ng-annotate": "0.8.0"
}
